on:
  push:
    branches:
    - master

jobs:
tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1
      
       name: Set up JDK 11
       - uses: actions/setup-java@v1 # устанавливаем JDK
        with:
          java-version: 11 # версия для установки

      - name: Install dependencies and run tests
        run: npm install && npm test
        
 
      
